# Generated by Django 3.1.13 on 2021-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
